# Generated by Django 5.1.2 on 2026-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_link_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image',
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
