# Generated by Django 5.1.2 on 2026-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collection_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
