# Generated by Django 5.1.2 on 2026-06-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
