# Generated by Django 5.1.2 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_disabled_at_to_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='admin_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
